"""Type stub for the parts of Apache DataSketches this package uses.

``datasketches`` ships no ``py.typed`` marker, so under ``mypy --strict`` every import of
it is an ``import-untyped`` error. The root ``pyproject.toml`` already carries exactly
this override for ``pyarrow``, and ``datasketches`` needs the same — but that file
belongs to A0 and universal rule 1 says this package does not edit it. See
``docs/change-requests/CR-A2-datasketches-needs-a-mypy-override.md``.

A PEP 561 stub-only package solves it without touching anything outside
``packages/godwit-sketch``: ``packages/godwit-sketch/src`` is already on the repo's
``mypy_path``, so a ``datasketches-stubs`` directory beside ``godwit_sketch`` is found
automatically. It is not shipped — the wheel build packages ``src/godwit_sketch`` only.

**Why the classes are declared twice.** Upstream's class names are lowercase
(``compact_theta_sketch``), which trips ruff's `N801`, and universal rule 3 leaves no
`# noqa` available. A stub also cannot simply rename them, because the names have to
match what the library exports. So each class is declared once with a conforming name
and then bound to the name upstream actually uses. mypy follows the alias, callers get
real types, and no rule is suppressed.

Deliberately partial: it covers the Theta surface this package calls and nothing else,
rather than transcribing a library we use a corner of. A typo in an unused DataSketches
API will not be caught here. That is contained by there being exactly one module that
touches the library (``godwit_sketch.distinct``) and by ``tests/test_contract_gaps.py``
exercising the real library rather than this stub.

Delete this directory when the root override lands.
"""

from collections.abc import Buffer

class CompactThetaSketch:
    @property
    def num_retained(self) -> int: ...
    @property
    def theta(self) -> float: ...
    def get_estimate(self) -> float: ...
    def get_lower_bound(self, num_std_devs: int) -> float: ...
    def get_upper_bound(self, num_std_devs: int) -> float: ...
    def is_empty(self) -> bool: ...
    def is_estimation_mode(self) -> bool: ...
    def is_ordered(self) -> bool: ...
    def serialize(self) -> bytes: ...
    def to_string(self) -> str: ...
    @staticmethod
    def deserialize(data: Buffer, seed: int = ...) -> CompactThetaSketch: ...

class UpdateThetaSketch:
    def __init__(self, lg_k: int = ..., p: float = ..., seed: int = ...) -> None: ...
    @property
    def num_retained(self) -> int: ...
    def update(self, datum: str | int | float | bytes) -> None: ...
    def compact(self, ordered: bool = ...) -> CompactThetaSketch: ...
    def get_estimate(self) -> float: ...
    def is_empty(self) -> bool: ...
    def is_estimation_mode(self) -> bool: ...
    def trim(self) -> None: ...

class ThetaUnion:
    def __init__(self, lg_k: int = ..., p: float = ..., seed: int = ...) -> None: ...
    def update(self, sketch: CompactThetaSketch | UpdateThetaSketch) -> None: ...
    def get_result(self, ordered: bool = ...) -> CompactThetaSketch: ...

# The names the library actually exports.
compact_theta_sketch = CompactThetaSketch
update_theta_sketch = UpdateThetaSketch
theta_union = ThetaUnion
