"""Godwit contracts: the shared vocabulary every other package codes against.

Owner: A0. Plane: both -- these types travel across the boundary, which is exactly why
they carry their own sensitivity.

This package depends on Pydantic and the standard library. Nothing else. It performs no
I/O, reads no clock and generates no randomness. If you are adding something here that
needs any of those, it belongs in your own package.

Read ``docs/ARCHITECTURE.md`` first. Then, in order:

1. :mod:`godwit_contracts.taint` -- the sensitivity system. Everything depends on it.
2. :mod:`godwit_contracts.safe` -- why the LLM adapter takes exactly one type.
3. :mod:`godwit_contracts.segment` -- the normalisation two agents must agree on.
4. :mod:`godwit_contracts.protocols` -- the twelve extension points and their laws.

If a contract is wrong, missing or impossible: do not fix it here. Write
``docs/change-requests/CR-<your-id>-<slug>.md`` and implement against the contract as
written, with an xfail test showing what you needed.
"""

from __future__ import annotations

from godwit_contracts.common import (
    ArtifactId,
    AuditId,
    CandidateId,
    ContentHash,
    DeploymentId,
    GodwitModel,
    Instant,
    NonNegFloat,
    NonNegInt,
    PatternId,
    Plane,
    Probability,
    ProbeId,
    ProbeKey,
    RunId,
    ScalarValue,
    SegmentKey,
    SnapshotId,
    SourceId,
    Version,
    canonical_json,
    content_hash,
    require_utc,
)
from godwit_contracts.cost import CostBudget, CostSpend
from godwit_contracts.discovery import (
    Alert,
    AlertQueue,
    Candidate,
    CoverageScope,
    Evidence,
    EvidenceKind,
    Explanation,
    Feedback,
    Label,
    LabelSet,
    LabelValue,
    Lineage,
    Pattern,
    PatternLifecycle,
    Severity,
    Verdict,
    label_index,
)
from godwit_contracts.errors import (
    BudgetExceededError,
    EgressDeniedError,
    ForgedObjectError,
    GodwitContractError,
    IssuerAlreadyClaimedError,
    MemorisationAuditFailedError,
    SealedConstructionError,
)
from godwit_contracts.features import (
    FeatureKind,
    FeatureSet,
    FeatureSpec,
    FillPolicy,
    PointInTimeRule,
)
from godwit_contracts.governance import (
    ApprovalRequest,
    ApprovalStatus,
    AuditEvent,
    DatasourceConfig,
    DatasourceKind,
    Destination,
    EgressRecord,
    Guardrail,
    GuardrailAction,
    GuardrailAttribute,
    GuardrailCondition,
    GuardrailPredicate,
    GuardrailScope,
    RedactionAction,
    RedactionPolicy,
    RedactionRule,
    SecretProvider,
    SecretRef,
)
from godwit_contracts.probe import ProbeKind, ProbeSpec, probe_key
from godwit_contracts.protocols import (
    Detector,
    EgressGate,
    Evaluator,
    FeatureComputer,
    FeatureMatrixRef,
    LLMAdapter,
    LLMResponse,
    ModelRegistry,
    PatternStore,
    Predictor,
    Redactor,
    Sketch,
    SourceAdapter,
    Trainer,
)
from godwit_contracts.safe import (
    SafePayload,
    SafePayloadIssuer,
    SafeScalar,
    claim_safe_payload_issuer,
    issuer_claimant,
)
from godwit_contracts.segment import (
    Operator,
    Predicate,
    Segment,
    canonical_column,
    canonical_scalar,
    canonical_segment,
    segment_key,
)
from godwit_contracts.serving import (
    Deployment,
    DeploymentMode,
    DeploymentStatus,
    FeatureAttribution,
    Prediction,
)
from godwit_contracts.sketch import (
    ErrorBound,
    SketchBundle,
    SketchEnvelope,
    SketchKind,
)
from godwit_contracts.source import (
    ColumnProfile,
    ColumnRef,
    ColumnRole,
    JoinEdge,
    LogicalType,
    PiiClass,
    SnapshotRef,
    SourceKind,
    SourceRef,
    TableProfile,
)
from godwit_contracts.taint import (
    ACQUISITION_MINIMUM_SENSITIVITY,
    Acquisition,
    Provenance,
    Sensitivity,
    Tainted,
    data_value,
    derived_statistic,
    egress_risk_rank,
    most_sensitive,
    schema_name,
    token,
)
from godwit_contracts.training import (
    REQUIRED_MEMORISATION_CHECKS,
    ArtifactFormat,
    DeployableModel,
    EvaluationReport,
    MemorisationAudit,
    MemorisationCheck,
    MemorisationCheckKind,
    ModelArtifact,
    ModelCard,
    Objective,
    SliceMetric,
    SplitKind,
    SplitSpec,
    TrainingRun,
    TrainingStatus,
    TrainingTask,
    certify_deployable,
)

__version__ = "0.1.0"

__all__ = [
    "ACQUISITION_MINIMUM_SENSITIVITY",
    "REQUIRED_MEMORISATION_CHECKS",
    "Acquisition",
    "Alert",
    "AlertQueue",
    "ApprovalRequest",
    "ApprovalStatus",
    "ArtifactFormat",
    "ArtifactId",
    "AuditEvent",
    "AuditId",
    "BudgetExceededError",
    "Candidate",
    "CandidateId",
    "ColumnProfile",
    "ColumnRef",
    "ColumnRole",
    "ContentHash",
    "CostBudget",
    "CostSpend",
    "CoverageScope",
    "DatasourceConfig",
    "DatasourceKind",
    "DeployableModel",
    "Deployment",
    "DeploymentId",
    "DeploymentMode",
    "DeploymentStatus",
    "Destination",
    "Detector",
    "EgressDeniedError",
    "EgressGate",
    "EgressRecord",
    "ErrorBound",
    "EvaluationReport",
    "Evaluator",
    "Evidence",
    "EvidenceKind",
    "Explanation",
    "FeatureAttribution",
    "FeatureComputer",
    "FeatureKind",
    "FeatureMatrixRef",
    "FeatureSet",
    "FeatureSpec",
    "Feedback",
    "FillPolicy",
    "ForgedObjectError",
    "GodwitContractError",
    "GodwitModel",
    "Guardrail",
    "GuardrailAction",
    "GuardrailAttribute",
    "GuardrailCondition",
    "GuardrailPredicate",
    "GuardrailScope",
    "Instant",
    "IssuerAlreadyClaimedError",
    "JoinEdge",
    "LLMAdapter",
    "LLMResponse",
    "Label",
    "LabelSet",
    "LabelValue",
    "Lineage",
    "LogicalType",
    "MemorisationAudit",
    "MemorisationAuditFailedError",
    "MemorisationCheck",
    "MemorisationCheckKind",
    "ModelArtifact",
    "ModelCard",
    "ModelRegistry",
    "NonNegFloat",
    "NonNegInt",
    "Objective",
    "Operator",
    "Pattern",
    "PatternId",
    "PatternLifecycle",
    "PatternStore",
    "PiiClass",
    "Plane",
    "PointInTimeRule",
    "Predicate",
    "Prediction",
    "Predictor",
    "Probability",
    "ProbeId",
    "ProbeKey",
    "ProbeKind",
    "ProbeSpec",
    "Provenance",
    "RedactionAction",
    "RedactionPolicy",
    "RedactionRule",
    "Redactor",
    "RunId",
    "SafePayload",
    "SafePayloadIssuer",
    "SafeScalar",
    "ScalarValue",
    "SealedConstructionError",
    "SecretProvider",
    "SecretRef",
    "Segment",
    "SegmentKey",
    "Sensitivity",
    "Severity",
    "Sketch",
    "SketchBundle",
    "SketchEnvelope",
    "SketchKind",
    "SliceMetric",
    "SnapshotId",
    "SnapshotRef",
    "SourceAdapter",
    "SourceId",
    "SourceKind",
    "SourceRef",
    "SplitKind",
    "SplitSpec",
    "TableProfile",
    "Tainted",
    "Trainer",
    "TrainingRun",
    "TrainingStatus",
    "TrainingTask",
    "Verdict",
    "Version",
    "__version__",
    "canonical_column",
    "canonical_json",
    "canonical_scalar",
    "canonical_segment",
    "certify_deployable",
    "claim_safe_payload_issuer",
    "content_hash",
    "data_value",
    "derived_statistic",
    "egress_risk_rank",
    "issuer_claimant",
    "label_index",
    "most_sensitive",
    "probe_key",
    "require_utc",
    "schema_name",
    "segment_key",
    "token",
]
